---
  - name: prompt in ansible
    hosts: local
    connection: local
    vars_prompt:
    - name: username
      prompt: Enter Username
      private: false

    - name: password
      prompt: Enter password
      private: true
      
    tasks:
    - name: print username and password
      ansible.builtin.debug:
        msg: "User name is : {{ username }} and password is: {{ password }}"