---
  - name: loops
    hosts: local
    connection: local
    become: yes
    tasks:
    - name: using loops
      ansible.builtin.debug:
        msg: "Hello, {{ item }}" #item is resered keyword here
      loop:
      - Ramesh
      - Naresh
      - Suresh
      - Harish
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
      - { name: 'nginx', state: 'present'}
      - { name: 'zip', state: 'present'}